import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavLinks from "$lib/ui/nav-links";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="https://assets.pokemon.com/static2/_ui/img/favicon.ico" />
      </head>
      <body className={inter.className}>
        <NavLinks />
        <main className="container m-auto mt-20">
          {children}
        </main>

      </body>
    </html>
  );
}
